{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0009d3e4-af39-4e9a-a8a0-f587180f8f77",
   "metadata": {},
   "source": [
    "Q1"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d59d6824-38f0-471b-9a20-5553e921afac",
   "metadata": {},
   "source": [
    "In object-oriented programming, including in languages like Python, exceptions are used to handle and communicate errors and exceptional conditions that may occur during the execution of a program. When creating custom exceptions, it is generally recommended to derive them from the base `Exception` class or one of its subclasses.\n",
    "\n",
    "Here are a few reasons why it is advisable to use the `Exception` class as the base class for custom exceptions:\n",
    "\n",
    "1. Standardized Handling: By inheriting from the `Exception` class, your custom exception becomes part of the existing exception hierarchy. This ensures that your custom exception can be handled using the same exception handling mechanisms that are available for built-in exceptions. It allows you to catch and handle your custom exception in a consistent manner alongside other exceptions in your program.\n",
    "\n",
    "2. Consistent Interface: The `Exception` class provides a set of methods and properties that allow for consistent and standardized handling of exceptions. These include methods like `__str__()` for getting a string representation of the exception, `args` for accessing the exception arguments, and others. By inheriting from `Exception`, your custom exception inherits these methods, making it easier for developers to work with and understand your custom exception.\n",
    "\n",
    "3. Compatibility: Deriving from the `Exception` class ensures that your custom exception is compatible with existing exception handling code. Since many libraries and frameworks are built to handle exceptions based on the `Exception` class or its subclasses, using it as the base class for your custom exception increases the likelihood that your exception will be correctly caught and handled by existing error handling mechanisms.\n",
    "\n",
    "4. Clarity and Readability: By using the `Exception` class, you make your code more readable and self-explanatory. When other developers encounter your custom exception, they will immediately recognize it as an exception based on the familiar inheritance from `Exception`. This promotes code maintainability and reduces confusion when others need to work with your code.\n",
    "\n",
    "In summary, using the `Exception` class as the base class for custom exceptions provides a standardized and consistent way to handle and communicate errors in your code. It ensures compatibility with existing exception handling mechanisms, promotes code clarity, and enables your custom exception to be handled in a similar manner as built-in exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a42b96a6-b086-4f01-bd81-9e40e9d2f915",
   "metadata": {},
   "source": [
    "Q2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e57ad31f-cfa7-4e36-809b-5a1fe9eaec31",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "    Exception\n",
      "        TypeError\n",
      "            FloatOperation\n",
      "            MultipartConversionError\n",
      "        StopAsyncIteration\n",
      "        StopIteration\n",
      "        ImportError\n",
      "            ModuleNotFoundError\n",
      "            ZipImportError\n",
      "        OSError\n",
      "            ConnectionError\n",
      "                BrokenPipeError\n",
      "                ConnectionAbortedError\n",
      "                ConnectionRefusedError\n",
      "                ConnectionResetError\n",
      "                    RemoteDisconnected\n",
      "            BlockingIOError\n",
      "            ChildProcessError\n",
      "            FileExistsError\n",
      "            FileNotFoundError\n",
      "            IsADirectoryError\n",
      "            NotADirectoryError\n",
      "            InterruptedError\n",
      "                InterruptedSystemCall\n",
      "            PermissionError\n",
      "            ProcessLookupError\n",
      "            TimeoutError\n",
      "            UnsupportedOperation\n",
      "            itimer_error\n",
      "            herror\n",
      "            gaierror\n",
      "            SSLError\n",
      "                SSLCertVerificationError\n",
      "                SSLZeroReturnError\n",
      "                SSLWantWriteError\n",
      "                SSLWantReadError\n",
      "                SSLSyscallError\n",
      "                SSLEOFError\n",
      "            Error\n",
      "                SameFileError\n",
      "            SpecialFileError\n",
      "            ExecError\n",
      "            ReadError\n",
      "            URLError\n",
      "                HTTPError\n",
      "                ContentTooShortError\n",
      "            BadGzipFile\n",
      "        EOFError\n",
      "            IncompleteReadError\n",
      "        RuntimeError\n",
      "            RecursionError\n",
      "            NotImplementedError\n",
      "                ZMQVersionError\n",
      "                StdinNotImplementedError\n",
      "            _DeadlockError\n",
      "            BrokenBarrierError\n",
      "            BrokenExecutor\n",
      "                BrokenThreadPool\n",
      "            SendfileNotAvailableError\n",
      "            ExtractionError\n",
      "            VariableError\n",
      "        NameError\n",
      "            UnboundLocalError\n",
      "        AttributeError\n",
      "            FrozenInstanceError\n",
      "        SyntaxError\n",
      "            IndentationError\n",
      "                TabError\n",
      "        LookupError\n",
      "            IndexError\n",
      "            KeyError\n",
      "                NoSuchKernel\n",
      "                UnknownBackend\n",
      "            CodecRegistryError\n",
      "        ValueError\n",
      "            UnicodeError\n",
      "                UnicodeEncodeError\n",
      "                UnicodeDecodeError\n",
      "                UnicodeTranslateError\n",
      "            UnsupportedOperation\n",
      "            JSONDecodeError\n",
      "            SSLCertVerificationError\n",
      "            Error\n",
      "            UnsupportedDigestmodError\n",
      "            IllegalMonthError\n",
      "            IllegalWeekdayError\n",
      "            ParserError\n",
      "            ClassNotFound\n",
      "            ClipboardEmpty\n",
      "            MessageDefect\n",
      "                NoBoundaryInMultipartDefect\n",
      "                StartBoundaryNotFoundDefect\n",
      "                CloseBoundaryNotFoundDefect\n",
      "                FirstHeaderLineIsContinuationDefect\n",
      "                MisplacedEnvelopeHeaderDefect\n",
      "                MissingHeaderBodySeparatorDefect\n",
      "                MultipartInvariantViolationDefect\n",
      "                InvalidMultipartContentTransferEncodingDefect\n",
      "                UndecodableBytesDefect\n",
      "                InvalidBase64PaddingDefect\n",
      "                InvalidBase64CharactersDefect\n",
      "                InvalidBase64LengthDefect\n",
      "                HeaderDefect\n",
      "                    InvalidHeaderDefect\n",
      "                    HeaderMissingRequiredValue\n",
      "                    NonPrintableDefect\n",
      "                    ObsoleteHeaderDefect\n",
      "                    NonASCIILocalPartDefect\n",
      "                    InvalidDateDefect\n",
      "            MacroToEdit\n",
      "            InvalidFileException\n",
      "            UnequalIterablesError\n",
      "            InvalidVersion\n",
      "            _InvalidELFFileHeader\n",
      "            InvalidWheelFilename\n",
      "            InvalidSdistFilename\n",
      "            InvalidSpecifier\n",
      "            InvalidMarker\n",
      "            UndefinedComparison\n",
      "            UndefinedEnvironmentName\n",
      "            InvalidRequirement\n",
      "                RequirementParseError\n",
      "            InvalidVersion\n",
      "        AssertionError\n",
      "        ArithmeticError\n",
      "            FloatingPointError\n",
      "            OverflowError\n",
      "            ZeroDivisionError\n",
      "                DivisionByZero\n",
      "                DivisionUndefined\n",
      "            DecimalException\n",
      "                Clamped\n",
      "                Rounded\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Inexact\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Subnormal\n",
      "                    Underflow\n",
      "                DivisionByZero\n",
      "                FloatOperation\n",
      "                InvalidOperation\n",
      "                    ConversionSyntax\n",
      "                    DivisionImpossible\n",
      "                    DivisionUndefined\n",
      "                    InvalidContext\n",
      "        SystemError\n",
      "            CodecRegistryError\n",
      "        ReferenceError\n",
      "        MemoryError\n",
      "        BufferError\n",
      "        Warning\n",
      "            UserWarning\n",
      "                GetPassWarning\n",
      "                FormatterWarning\n",
      "            EncodingWarning\n",
      "            DeprecationWarning\n",
      "                ProvisionalWarning\n",
      "            PendingDeprecationWarning\n",
      "            SyntaxWarning\n",
      "            RuntimeWarning\n",
      "                ProactorSelectorThreadWarning\n",
      "                UnknownTimezoneWarning\n",
      "                PEP440Warning\n",
      "            FutureWarning\n",
      "                ProvisionalCompleterWarning\n",
      "            ImportWarning\n",
      "            UnicodeWarning\n",
      "            BytesWarning\n",
      "            ResourceWarning\n",
      "            DeprecatedTzFormatWarning\n",
      "            PkgResourcesDeprecationWarning\n",
      "        _OptionError\n",
      "        _Error\n",
      "        error\n",
      "        Verbose\n",
      "        Error\n",
      "        SubprocessError\n",
      "            CalledProcessError\n",
      "            TimeoutExpired\n",
      "        TokenError\n",
      "        StopTokenizing\n",
      "        ClassFoundException\n",
      "        EndOfBlock\n",
      "        TraitError\n",
      "        Error\n",
      "        Error\n",
      "            CancelledError\n",
      "            TimeoutError\n",
      "            InvalidStateError\n",
      "        _GiveupOnSendfile\n",
      "        error\n",
      "        Incomplete\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "        LimitOverrunError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        Empty\n",
      "        Full\n",
      "        ArgumentError\n",
      "        ZMQBaseError\n",
      "            ZMQError\n",
      "                ContextTerminated\n",
      "                Again\n",
      "                InterruptedSystemCall\n",
      "            ZMQBindError\n",
      "            NotDone\n",
      "        PickleError\n",
      "            PicklingError\n",
      "            UnpicklingError\n",
      "        _Stop\n",
      "        ArgumentError\n",
      "        ArgumentTypeError\n",
      "        ConfigError\n",
      "            ConfigLoaderError\n",
      "                ArgumentError\n",
      "            ConfigFileNotFound\n",
      "        ConfigurableError\n",
      "            MultipleInstanceError\n",
      "        ApplicationError\n",
      "        error\n",
      "        TimeoutError\n",
      "        error\n",
      "        ReturnValueIgnoredError\n",
      "        KeyReuseError\n",
      "        UnknownKeyError\n",
      "        LeakedCallbackError\n",
      "        BadYieldError\n",
      "        ReturnValueIgnoredError\n",
      "        Return\n",
      "        InvalidPortNumber\n",
      "        error\n",
      "        LZMAError\n",
      "        RegistryError\n",
      "        _GiveupOnFastCopy\n",
      "        Error\n",
      "            NoSectionError\n",
      "            DuplicateSectionError\n",
      "            DuplicateOptionError\n",
      "            NoOptionError\n",
      "            InterpolationError\n",
      "                InterpolationMissingOptionError\n",
      "                InterpolationSyntaxError\n",
      "                InterpolationDepthError\n",
      "            ParsingError\n",
      "                MissingSectionHeaderError\n",
      "        NoIPAddresses\n",
      "        BadZipFile\n",
      "        LargeZipFile\n",
      "        BadEntryPoint\n",
      "        NoSuchEntryPoint\n",
      "        DuplicateKernelError\n",
      "        ErrorDuringImport\n",
      "        NotOneValueFound\n",
      "        CannotEval\n",
      "        OptionError\n",
      "        BdbQuit\n",
      "        Restart\n",
      "        ExceptionPexpect\n",
      "            EOF\n",
      "            TIMEOUT\n",
      "        PtyProcessError\n",
      "        FindCmdError\n",
      "        HomeDirError\n",
      "        ProfileDirError\n",
      "        IPythonCoreError\n",
      "            TryNext\n",
      "            UsageError\n",
      "            StdinNotImplementedError\n",
      "        InputRejected\n",
      "        GetoptError\n",
      "        ErrorToken\n",
      "        PrefilterError\n",
      "        AliasError\n",
      "            InvalidAliasError\n",
      "        Error\n",
      "            InterfaceError\n",
      "            DatabaseError\n",
      "                InternalError\n",
      "                OperationalError\n",
      "                ProgrammingError\n",
      "                IntegrityError\n",
      "                DataError\n",
      "                NotSupportedError\n",
      "        Warning\n",
      "        SpaceInInput\n",
      "        DOMException\n",
      "            IndexSizeErr\n",
      "            DomstringSizeErr\n",
      "            HierarchyRequestErr\n",
      "            WrongDocumentErr\n",
      "            InvalidCharacterErr\n",
      "            NoDataAllowedErr\n",
      "            NoModificationAllowedErr\n",
      "            NotFoundErr\n",
      "            NotSupportedErr\n",
      "            InuseAttributeErr\n",
      "            InvalidStateErr\n",
      "            SyntaxErr\n",
      "            InvalidModificationErr\n",
      "            NamespaceErr\n",
      "            InvalidAccessErr\n",
      "            ValidationErr\n",
      "        ValidationError\n",
      "        EditReadOnlyBuffer\n",
      "        _Retry\n",
      "        InvalidLayoutError\n",
      "        HeightIsUnknownError\n",
      "        ParserSyntaxError\n",
      "        InternalParseError\n",
      "        _PositionUpdatingFinished\n",
      "        SimpleGetItemNotFound\n",
      "        UncaughtAttributeError\n",
      "        HasNoContext\n",
      "        ParamIssue\n",
      "        _JediError\n",
      "            InternalError\n",
      "            WrongVersion\n",
      "            RefactoringError\n",
      "        OnErrorLeaf\n",
      "        InvalidPythonEnvironment\n",
      "        MessageError\n",
      "            MessageParseError\n",
      "                HeaderParseError\n",
      "                BoundaryError\n",
      "            MultipartConversionError\n",
      "            CharsetError\n",
      "        Error\n",
      "        HTTPException\n",
      "            NotConnected\n",
      "            InvalidURL\n",
      "            UnknownProtocol\n",
      "            UnknownTransferEncoding\n",
      "            UnimplementedFileMode\n",
      "            IncompleteRead\n",
      "            ImproperConnectionState\n",
      "                CannotSendRequest\n",
      "                CannotSendHeader\n",
      "                ResponseNotReady\n",
      "            BadStatusLine\n",
      "                RemoteDisconnected\n",
      "            LineTooLong\n",
      "        InteractivelyDefined\n",
      "        KillEmbedded\n",
      "        Error\n",
      "            NoSuchProcess\n",
      "                ZombieProcess\n",
      "            AccessDenied\n",
      "            TimeoutExpired\n",
      "        _Ipv6UnsupportedError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        DebuggerInitializationError\n",
      "        ExpatError\n",
      "        Error\n",
      "            ProtocolError\n",
      "            ResponseError\n",
      "            Fault\n",
      "        ParseBaseException\n",
      "            ParseException\n",
      "            ParseFatalException\n",
      "                ParseSyntaxException\n",
      "        RecursiveGrammarException\n",
      "        ResolutionError\n",
      "            VersionConflict\n",
      "                ContextualVersionConflict\n",
      "            DistributionNotFound\n",
      "            UnknownExtra\n",
      "        _Error\n",
      "        UnableToResolveVariableException\n",
      "        InvalidTypeInArgsException\n",
      "    GeneratorExit\n",
      "    SystemExit\n",
      "    KeyboardInterrupt\n",
      "    CancelledError\n",
      "    AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "\n",
    "# Print the Python Exception Hierarchy\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c8c11c14-f200-46d2-b44e-534adc32f720",
   "metadata": {},
   "source": [
    "Q3"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2074dda2-f62d-4f6b-9564-8d0e43b6314b",
   "metadata": {},
   "source": [
    "The ArithmeticError class is a base class for all errors related to arithmetic operations in Python. It itself is derived from the Exception class. The ArithmeticError class encompasses a range of specific arithmetic-related error classes. Here are two commonly encountered errors defined within the ArithmeticError class:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2962e865-9aa8-47c6-9e65-dd6a6d0676cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Cannot divide by zero\n",
      "Error: Result exceeds the maximum representable value\n"
     ]
    }
   ],
   "source": [
    "#Zero division error\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        print(\"Result:\", result)\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero\")\n",
    "\n",
    "divide_numbers(10, 0)\n",
    "\n",
    "\n",
    "#Overflow error\n",
    "import sys\n",
    "\n",
    "def calculate_factorial(n):\n",
    "    try:\n",
    "        result = 1\n",
    "        for i in range(1, n + 1):\n",
    "            result *= i\n",
    "            if result > sys.maxsize:\n",
    "                raise OverflowError\n",
    "        print(\"Factorial:\", result)\n",
    "    except OverflowError:\n",
    "        print(\"Error: Result exceeds the maximum representable value\")\n",
    "\n",
    "calculate_factorial(100000)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "48bb1079-4586-4f3d-ab15-6cbeca47dd7f",
   "metadata": {},
   "source": [
    "Q4"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3d0e6a94-213f-4821-8058-521ea8573e95",
   "metadata": {},
   "source": [
    "The LookupError class is a base class for exceptions that occur when a lookup or indexing operation fails. It serves as the parent class for specific lookup-related error classes such as KeyError and IndexError. The LookupError class is derived from the Exception class.\n",
    "\n",
    "Here are two examples of errors derived from LookupError:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ce586126-04e8-40f6-aa5c-4725997ffa50",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Key not found in dictionary\n",
      "Error: Index out of range\n"
     ]
    }
   ],
   "source": [
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']\n",
    "    print(\"Value:\", value)\n",
    "except KeyError:\n",
    "    print(\"Error: Key not found in dictionary\")\n",
    "\n",
    "    \n",
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[3]\n",
    "    print(\"Value:\", value)\n",
    "except IndexError:\n",
    "    print(\"Error: Index out of range\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fe95a1f3-cb67-4d57-a35e-d8db980f07b2",
   "metadata": {},
   "source": [
    "Q5"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9f9d4c3-c5af-42dc-b509-98bd1b036062",
   "metadata": {},
   "source": [
    "\n",
    "ImportError is an exception that occurs when an imported module or a part of it cannot be found or loaded during the import process in Python. It is raised when there is an issue locating or importing a module."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "22326719-1bac-4982-a73a-02dd7aef8784",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found or cannot be imported\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Error: Module not found or cannot be imported\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fdff1101-7d31-4fc7-8c3f-ebef765eeedd",
   "metadata": {},
   "source": [
    "Q6"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d778a614-092e-4829-a50d-6f8633965705",
   "metadata": {},
   "source": [
    "Certainly! Here are some best practices for exception handling in Python:\n",
    "\n",
    "1. Be specific in exception handling: Catch only the exceptions that you can handle and leave the rest for the higher-level handlers or the default exception handler. This helps avoid unintentionally hiding or suppressing errors and allows for more precise error handling.\n",
    "\n",
    "2. Use multiple except blocks: When catching exceptions, use multiple `except` blocks to handle different types of exceptions separately. This allows you to provide specific error handling logic for each exception type. Start with the most specific exceptions and then proceed to more general ones.\n",
    "\n",
    "3. Handle exceptions gracefully: Exception handling should aim to gracefully handle errors and provide meaningful feedback to users or log appropriate error messages for debugging purposes. Avoid simply printing the error message and terminating the program without proper context.\n",
    "\n",
    "4. Use finally block for cleanup: If there are any resources that need to be cleaned up, such as file handles or network connections, use a `finally` block to ensure that the cleanup code is executed, regardless of whether an exception was raised or not.\n",
    "\n",
    "5. Avoid catching generic exceptions: Avoid catching generic exceptions like `Exception` unless absolutely necessary. Catching too broad exceptions can make it harder to diagnose specific issues and may lead to unexpected behavior.\n",
    "\n",
    "6. Use context managers for resource management: Context managers, implemented using the `with` statement, provide a convenient way to manage resources like file handles or database connections. They ensure proper resource cleanup even if exceptions are raised within the block.\n",
    "\n",
    "7. Reraise exceptions selectively: In some cases, it may be necessary to catch an exception, perform some actions, and then reraise the same exception or a different one. When reraising, use the `raise` statement without any arguments to re-raise the caught exception with its original traceback.\n",
    "\n",
    "8. Use logging for error messages: Instead of printing error messages directly, consider using Python's logging module for more robust and flexible error message handling. It allows you to log errors with different levels, timestamps, and can be easily configured to write logs to files or other destinations.\n",
    "\n",
    "9. Document exception handling: Document the exceptions that your functions or methods may raise, either in the function docstring or as part of the function signature. This helps other developers understand the expected exceptions and handle them appropriately.\n",
    "\n",
    "10. Test exception handling scenarios: Write tests to verify that your exception handling code functions correctly. Include test cases for both expected exceptions and unexpected exceptions to ensure that your code behaves as intended in various error scenarios.\n",
    "\n",
    "By following these best practices, you can write more robust and maintainable code that handles exceptions effectively, provides clear error messages, and helps with troubleshooting and debugging."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17768f20-91ae-44bb-9aaf-f6b1832fd889",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
